version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo
    networks:
      - todoapp-network
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
      - ./backend/pom.xml:/app/pom.xml
    command: ./mvnw spring-boot:run # Démarre l'application avec rechargement à chaud

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - todoapp-network
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - todoapp-network
    volumes:
      - mongo_data:/data/db

networks:
  todoapp-network:
    driver: bridge

volumes:
  mongo_data:
